// Code generated by protoc-gen-go.
// source: conn_addr.proto
// DO NOT EDIT!

/*
Package game is a generated protocol buffer package.

It is generated from these files:
	conn_addr.proto
	log_in.proto

It has these top-level messages:
	ConnAddr
	LoginRequest
	LoginResponse
*/
package game

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnAddr struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConnAddr) Reset()                    { *m = ConnAddr{} }
func (m *ConnAddr) String() string            { return proto.CompactTextString(m) }
func (*ConnAddr) ProtoMessage()               {}
func (*ConnAddr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnAddr) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ConnAddr) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*ConnAddr)(nil), "game.ConnAddr")
}

func init() { proto.RegisterFile("conn_addr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0xcb,
	0x8b, 0x4f, 0x4c, 0x49, 0x29, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x4f, 0xcc,
	0x4d, 0x55, 0xd2, 0xe4, 0xe2, 0x70, 0x06, 0x4a, 0x38, 0x02, 0xc5, 0x85, 0xf8, 0xb9, 0xd8, 0x41,
	0xf2, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x42, 0x3c, 0x5c, 0x2c, 0x05, 0xf9,
	0x45, 0x25, 0x12, 0x4c, 0x40, 0x1e, 0x2b, 0x20, 0x00, 0x00, 0xff, 0xff, 0x31, 0xd3, 0x29, 0x93,
	0x42, 0x00, 0x00, 0x00,
}
